In [1]:
import numpy as np

In [2]:
 n1 = np.array([10, 20])
 n2 = np.array([30, 40])

In [3]:
np.sum([n1, n2])

100

In [4]:
np.sum([n1, n2], axis=0)

array([40, 60])

In [5]:
np.sum([n1, n2], axis=1)

array([30, 70])

In [6]:
n2 = np.array([10, 20, 30, 40, 50])
n2

array([10, 20, 30, 40, 50])

In [9]:
add = n2 + 1
add

array([11, 21, 31, 41, 51])

In [8]:
mul = n2 * 2
mul

array([ 20,  40,  60,  80, 100])

In [10]:
sub = n2 - 1
sub

array([ 9, 19, 29, 39, 49])

In [11]:
div = n2 / 2
div

array([ 5., 10., 15., 20., 25.])