In [19]:
import numpy as np

In [20]:
arr = np.array([1,2,3,5])

In [21]:
type(arr)

numpy.ndarray

In [22]:
arr

array([1, 2, 3, 5])

In [23]:
mat = np.zeros((5,5))

In [24]:
 mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
mat = np.full((2, 2), 10)
mat

array([[10, 10],
       [10, 10]])

In [26]:
rng = np.arange(10, 20)
rng

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
rng = np.arange(10, 50 ,5)
rng

array([10, 15, 20, 25, 30, 35, 40, 45])

In [28]:
n1 = np.random.randint(1, 100, 5)
n1

array([79, 75, 53, 55,  9])

In [29]:
n2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
n2.shape = (4, 2)
n2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])