In [1]:
import numpy as np

In [4]:
n1 = np.array([1, 2, 3, 4, 5, 6])
n2 = np.array([5, 6, 7, 8, 9, 10])

In [5]:
np.intersect1d(n1, n2)

array([5, 6])

In [6]:
np.setdiff1d(n1, n2)

array([1, 2, 3, 4])

In [7]:
np.setdiff1d(n2, n1)

array([ 7,  8,  9, 10])