In [1]:
import numpy as np

In [3]:
n1 = np.array([1, 2, 3, 4])
n2 = np.array([5, 6, 7, 8])

In [6]:
vstk = np.vstack((n1, n2))
vstk

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
hstk = np.hstack((n1, n2))
hstk

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
clstk = np.column_stack((n1, n2))
clstk

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])